config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    post 'add_user'
    resource :settings, only: [:edit, :update],
      controller: 'project/settings'
    resources :tasks, controller: 'project/tasks' do
      patch 'change_status', on: :member
    end
  end

  get 'visitors/index'

  devise_for :users
  root 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_secure_token


  belongs_to :owner, class_name: 'User'
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :tasks

  validates :title, presence: true

  after_create :add_owner_to_user_list  

  typed_store :settings, coder: DumbCoder do |s|
    s.boolean :enabled, default: true, null: false
    s.string :timezone, default: 'America/Phoenix', null: false
    s.boolean :collaborators_can_add_users, default: false, null: false
  end

  private

  def add_owner_to_user_list
    project_user = self.project_users.new
    project_user.user = owner
    project_user.access_level = :owner
    project_user.save
  end
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user

  attribute :access_level, :integer, default: 2

  enum access_level: [:owner, :collaborator, :viewer]


  def assigned_tasks
    project.tasks.where(assignee: user)
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :assignee, class_name: 'User'
  belongs_to :project

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id'
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :tasks, foreign_key: 'assignee_id'

  validates :email, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/project/settings_controller.rb
class Project::SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :check_privileges
  def edit
  end

  def update
    if @project.update(settings_params)
      redirect_to @project, notice: 'Settings updated!'
    else
      flash.now.alert = 'There was an error, please try again.'
      render :edit
    end
  end

  private

  def settings_params
    params.require(:project).permit(:timezone, :collaborators_can_add_users,
                                   :enabled)
  end

  def check_privileges
    has_access = ProjectUser.exists?(project: @project, user: current_user,
                                   access_level: 'owner')
    unless has_access
      redirect_to @project, alert: 'Sorry, only the project owner can change the settings.'
    end
  end

  def set_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/project/tasks_controller.rb
class Project::TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :change_status]
  def show

  end

  def new
    @task = @project.tasks.new
    authorize [:project, @task]
  end

  def create
    @task = @project.tasks.new(task_params)
    authorize [:project, @task]

    if @task.save!
      redirect_to @project, notice: 'Task has been added!'
    else
      render :new
    end
  end

  def edit
    authorize [:project, @task]
  end

  def update
    authorize [:project, @task]
    if @task.update!(task_params)
      redirect_to @project, notice: 'Task updated.'
    else
      render :edit
    end
  end

  def change_status
    if @task.complete?
      @task.update(complete: false)
    else
      @task.update(complete: true)
    end
    redirect_to @project
  end

  private

  def task_params
    params.require(:task).permit(:description, :assignee_id)
  end

  def set_project
    @project = Project.find params[:project_id]
  end

  def set_task
    @task = Task.find params[:id]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @owned_projects = current_user.owned_projects
  end

  def show
    @project = Project.includes(:owner).find(params[:id])
    authorize @project
  end

  def new
    @project = current_user.owned_projects.new
  end

  def create
    @project = current_user.owned_projects.new(project_params)

    if @project.save!
      redirect_to @project, notice: 'Project created successfully!'
    else
      flash.now.alert = 'One or more errors prevented the project from being saved.'
      render :new
    end
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]

    if @project.update(project_params)
      redirect_to @project, notice: 'Project updated successfully!'
    else
      flash.now.alert = 'One or more errors prevented this project from being updated. Please try again.'
      render :edit
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.destroy
      redirect_to projects_url, notice: "Project [ID: #{@project.id}] has been deleted."
    else
      redirect_to @project, alert: 'This project could not be deleted.'
    end
  end

  def add_user
    @project = Project.find params[:project_id]
    @outcome = Projects::AddUser.run(user_params)

    respond_to do |format|
      format.html do
        if @outcome.valid?
          redirect_to @project, notice: 'User added!'
        else
          flash.now.alert = 'One or more errors prevented this user from being added.'
          render :show
        end
      end

      format.js do
        if @outcome.valid?
          render :show
        else
          render :new
        end
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :start_date)
  end

  def user_params
    params.require(:user).permit(:access_level, :email).merge!({project: @project})
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_nav_contents.html.slim
.topnav
  = active_link_to 'Home', root_path, active: :exact
  = active_link_to 'Projects', projects_path
  = active_link_to 'Sign in', new_user_session_path if !current_user
  = active_link_to 'Sign out', destroy_user_session_path,
    method: :delete if current_user

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <div class="navigation">
    <%= render 'nav_contents' %>
  </div>
  <%= render "flashes" -%>
  <div class="container">
    <%= yield %>
    <%= render "javascript" %>
    <%= render "css_overrides" %>
  </div>
</body>
</html>

app/views/project/settings/edit.html.slim
h1 Project::Settings#edit
= form_with model: @project, url: project_settings_path(@project),
  local: true, method: :patch do |f|
  = f.label :timezone
  = f.text_field :timezone

  = f.label :enabled
  = f.check_box :enabled

  = f.label :collaborators_can_add_users
  = f.check_box :collaborators_can_add_users
  hr
  = f.submit 'Change Settings'
= button_to 'Back to Project', @project, method: :get

app/views/project/tasks/_form.html.slim
= form_for @task, url: url do |f|

  = f.label :description
  = f.text_field :description

  = f.label :assignee_id
  = f.collection_select :assignee_id, @project.users, :id, :email

  = f.submit

app/views/project/tasks/edit.html.slim
= render 'form', url: project_task_path([@project, @path])

app/views/project/tasks/new.html.slim
.container
  .half-centered
    h1 Add Task &mdash; <em>#{@project.title}</em>

    = render 'form', url: project_tasks_path(@project)

app/views/projects/_form.html.slim
.container
  .half-centered
    = form_with model: @project, local: true do |f|
      = f.label :title
      = f.text_field :title

      = f.label :description
      = f.text_area :description

      = f.label :start_date
      = f.date_select :start_date

      = f.submit

app/views/projects/edit.html.slim
h1 Projects#edit
p Find me in app/views/projects/edit.html.slim

app/views/projects/index.html.slim
.container
  .half-centered
    table
      thead
        tr
          th Title
          th[colspan="3"] Actions
      tbody
        - @owned_projects.each do |op|
          tr
            td = op.title
            td = link_to 'Show', op
            td = link_to 'Edit', edit_project_path(op)
            td = link_to 'Delete', op, method: :delete
    = button_to 'New Project', new_project_path, method: :get

app/views/projects/new.html.slim
.container
  .half-centered
    h1 Create New Project
= render 'form'

app/views/projects/new.js.erb
alert('Moo!');

app/views/projects/show.html.slim
.container 
  .half-centered.details
    h1 View Project
    table
      tr
        th Title
        td = @project.title
      - if @project.start_date.present?
        tr
          th Start Date
          td = @project.start_date
      tr
        th Project Token
        td = @project.token
      tr
        th Description
        td = @project.description
      - if @project.owner == current_user
        tr
          th
          td = link_to 'Change Project Settings',
          edit_project_settings_path(@project)

.container
  .half-centered.details
    h1 Tasks
    table
      thead
        tr
          th
          th Description
          th Assignee
      tbody
        - @project.tasks.includes(:assignee).each do |task|
          tr
            - if task.complete?
              td
                = link_to 'Complete', 
                  change_status_project_task_path(@project, task),
                  method: :patch
            - else


              td
                = link_to 'Incomplete', 
                  change_status_project_task_path(@project, task),
                  method: :patch
            td = task.description

            td = task.assignee.email
    = button_to 'Add Task', new_project_task_path(@project), method: :get

- if current_user == @project.owner
  .container
    .half-centered.details
      h1 Access List
      table.access_list
        thead
          tr
            th Email
            th Access Level
        tbody
          - @project.project_users.each do |pu|
            tr
              td = pu.user.email
              td = pu.access_level
      hr
      h3 Add User
      = form_with scope: :user, url: project_add_user_path(@project)\
          do |f|
        = f.label :email
        = f.text_field :email

        = f.label :access_level
        = f.select :access_level, ProjectUser.access_levels.keys

        = f.submit 'Add User'

app/views/projects/show.js.erb
$('table.access_list').append('<tr><td><%= @outcome.result.user.email %></td><td><%= @outcome.result.access_level %></td></tr>');

$('input[name="user[email]"]').val('');

alert('Cow!');

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
        <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
        <li id="js-navigation-more" class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
            <li class="more"><a href="javascript:void(0)">Item with submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu Item</a></li>
                <li><a href="javascript:void(0)">Another Item</a></li>
              </ul>
            </li>
            <li class="more"><a href="javascript:void(0)">Another submenu</a>
              <ul class="submenu">
                <li><a href="javascript:void(0)">Sub-submenu</a></li>
                <li><a href="javascript:void(0)">An Item</a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
    </div>
  </div>
</header>

app/views/visitors/index.html.slim
h1 Welcome to Workollab!
- if current_user
  p Hello, #{current_user.email}!
  = link_to 'Sign out', destroy_user_session_path, method: :delete
- else
  = link_to 'Sign in', new_user_session_path